server:
   port: 9090
spring:
   profiles:
      active: jdbc
   datasource:
      url: jdbc:mariadb://localhost:3360/config
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
         connection-timeout: 5000
         maximum-pool-size: 10
   cloud:
      config:
         server:
            jdbc:
               sql: SELECT KEY, VALUE FROM PROPERTIES WHERE APPLICATION=? AND PROFILE=? AND LABEL=?
               order: 1