CREATE TABLE PROPERTIES (
ID INTEGER NOT NULL AUTO_INCREMENT, 
CREATED_ON DATETIME,
APPLICATION VARCHAR(255), 
PROFILE VARCHAR(255), 
LABEL VARCHAR(255), 
KEY VARCHAR(255), 
VALUE VARCHAR(255), 
PRIMARY KEY (id));